### ISSUE TITLE
Support X / Y Positions

### ISSUE THREAD

**Issue by amcdnl** [wellyshen/react-cool-dimensions#180]
It would be great if the hook would return the X / Y positions too.

```
const [itemRef, { x }] = useDimensios({ liveMeasure: false });
```

Example: https://www.npmjs.com/package/react-use-dimensions

**Comment by wellyshen** [comment]
@amcdnl The return dimensions are provided by the [ResizeObserverEntry](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry) of the [Resize Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API). Unfortunately the API doesn't supports the `x/y` properties.
