### ISSUE TITLE
Add `ref` to`Return`

### ISSUE THREAD

**Issue by with-heart** [wellyshen/react-cool-dimensions#22]
# Feature Request

## Describe the Feature

Since `ref` is always required, `react-cool-dimensions` should provide that as part of its API. 

## Describe the Solution You'd Like

`react-cool-dimensions` creates `ref` internally and returns it as part of `Return`, which the consumer then attaches to their container. 

Using the "Basic Use Case" from `README`, it'd look like this:

```jsx
const App = () => {
  const { ref, width, height, entry, unobserve, observe } = useDimensions({
    onResize: ({ width, height, entry, unobserve, observe }) => {
      // Triggered whenever the size of the target is changed
    },
  });

  return (
    <div ref={ref}>
      Hi! My width is {width}px and height is {height}px
    </div>
  );
};
```

## Additional Information

Obviously not something that's all that important, but it makes the API a little cleaner and easier to use.

**Comment by wellyshen** [comment]
@with-heart Thank you for your feedback. I used count the `ref` as a part of API in some of my other libraries, but I removed it. The reason is some people might need to share a `ref` for different utilities. So I'd it's better to keep it outside.

**Comment by with-heart** [comment]
Gotcha! That makes perfect sense

**Comment by wellyshen** [comment]
@with-heart Sorry for late, hope you [like it](https://github.com/wellyshen/react-cool-dimensions/releases/tag/v1.1.0).
