### ISSUE TITLE
Set Resize Obeserver box

### ISSUE THREAD

**Issue by hipstersmoothie** [wellyshen/react-cool-dimensions#24]
# Bug Report

I need to be able to set the box that resize observers uses

## Describe the Bug

Right now I can't get it to respect `box-sizing: border-box`

## How to Reproduce

Try to size an element with `box-sizing: border-box`

## Expected Behavior

Should be able to make it take padding into account

**Comment by wellyshen** [comment]
@hipstersmoothie [Here you are](https://github.com/wellyshen/react-cool-dimensions/releases/tag/v0.6.0).

**Comment by hipstersmoothie** [comment]
Thanks!
