### ISSUE TITLE
react-cool-dimensions shows 0 width & 0 height on mobile browsers 

### ISSUE THREAD

**Issue by kimbaudi** [wellyshen/react-cool-dimensions#258]
# Bug Report

react-cool-dimensions shows 0 width & 0 height on mobile browsers. it works fine in desktop, but not mobile.

## How to Reproduce

1. create react app (`npx create-react-app my-app`)
2. install `react-cool-dimensions` (`cd my-app && npm i -S react-cool-dimensions`)
3. use `react-cool-dimensions` to display width & height of element(s) (i.e., `<header>`, `<footer>`

## Code demonstrating bug

```jsx
import React, { useRef } from "react";
import useDimensions from "react-cool-dimensions";

function App() {
  const headRef = useRef();
  const footRef = useRef();
  const { height: headHeight, width: headWidth } = useDimensions({
    ref: headRef,
    useBorderBoxSize: true,
  });
  const { height: footHeight, width: footWidth } = useDimensions({
    ref: footRef,
    useBorderBoxSize: false,
  });
  return (
    <div>
      <header ref={headRef}>this is the header</header>
      <main>this is main</main>
      <footer ref={footRef}>
        this is footer
        <br />
        headWidth: {headWidth}
        <br />
        headHeight: {headHeight}
        <br />
        footWidth: {footWidth}
        <br />
        footHeight: {footHeight}
      </footer>
    </div>
  );
}

export default App;
```

[react-cool-dim-test-main.zip](https://github.com/wellyshen/react-cool-dimensions/files/5579913/react-cool-dim-test-main.zip)

## Expected Behavior

header & footer width & height should not be 0 on mobile.

## Screenshots

Desktop:

![desktop-browser](https://user-images.githubusercontent.com/1864092/99910897-8fe04e00-2ca5-11eb-9d6c-c53714bbe98d.png)

Mobile:

![mobile-browser](https://user-images.githubusercontent.com/1864092/99910902-95d62f00-2ca5-11eb-8c5d-f8f97209f962.jpg)

**Comment by wellyshen** [comment]
@kimbaudi It works on my iPhone + Google Chrome, can you provide the information of your environment?

**Comment by kimbaudi** [comment]
It doesn't work for me. I tested on my iPhone 6 plus (Safari, Chrome, Firefox) and on my Samsung Galaxy S7 edge (Chrome, Firefox, Opera, Brave, Samsung Internet, etc). Try opening <https://cooldimtest.netlify.app> on a mobile browser... it shows 0 for widths & heights. I've already attached screenshots above, uploaded a .zip file with minimal reproducible code, and is currently available to view demo on <https://cooldimtest.netlify.app>

**Comment by wellyshen** [comment]
@kimbaudi I have tested your demo app, it still works like the screenshot:
![IMG_3602](https://user-images.githubusercontent.com/21308003/100250482-ad990600-2f78-11eb-95d3-f2521563a04f.PNG)

What's your mobile safari version? If your mobile browsers do not support the ResizeObserver (see [here](https://caniuse.com/resizeobserver)), then you need to use [polyfill](https://github.com/wellyshen/react-cool-dimensions#resizeobserver-polyfill).

**Comment by kimbaudi** [comment]
@wellyshen - Thanks for the link to the caniuse website that shows support for resize observer. I realize that my iphone 6 plus has safari 12 so it doesn't support resize observer unless I use the polyfill. It works fine on my galaxy s7 edge (chrome, firefox, brave, opera, samsung internet). I thought it didn't work on my android device, but I guess I was wrong. I'll close this now.
