### ISSUE TITLE
Doesn't handle component mounted after start

### ISSUE THREAD

**Issue by jwalton** [wellyshen/react-cool-dimensions#299]
# Bug Report

## Describe the Bug

If the `ref.current` is `undefined` the first pass through, we'll [not set up the observer](https://github.com/wellyshen/react-cool-dimensions/blob/master/src/index.ts#L91), and we [won't re-run this effect](https://github.com/wellyshen/react-cool-dimensions/blob/master/src/index.ts#L165) if the ref.current changes (only if the ref itself changes), so in this case we'll never get the width and height for an element.

## How to Reproduce

An easy way to reproduce this is to try to measure the dimensions of an element that mounts after the initial render:

```ts
const { ref, width, height } = useDimensions();
const [ showBox, setShowBox ] = useState(false);

return <div>
  <button onClick={() => setShowBox(true)}>Show!</button>
  { showBox && <div ref={ref}>Tada! {width}x{height}</div> }
</div>;
```

## Expected Behavior

Should get the width and height of the element.

## Additional Information

This is why a lot of similar libraries don't let you pass in a ref - they return a ref to you which is really a `(el: HTMLElement) => void`, and when it gets called they can handle the initial mounting of the component.

**Comment by durdo** [comment]
I'm having this exact problem. Do we have any feedback? Maybe a suggested workaround?

Thanks!

**Comment by jwalton** [comment]
This is the quick-and-dirty "useElementSize" I'm using in my app right now:

```ts
import { useCallback, useLayoutEffect, useRef, useState } from 'react';

export interface ElementSize {
  width: number | undefined;
  height: number | undefined;
}

const UNDEFINED_SIZE = {
  width: undefined,
  height: undefined,
};

Object.freeze(UNDEFINED_SIZE);

// Convert an HTMLElement to a ElementSize.
function elToSize(el: HTMLElement | null | undefined) {
  if (el) {
    return {
      width: el.offsetWidth,
      height: el.offsetHeight,
    };
  } else {
    return UNDEFINED_SIZE;
  }
}

/**
 * Returns the width and height of an HTML Element.
 *
 * @returns a [size, ref] object.
 * @example
 *     const [ size, ref ] = useElementSize();
 *     return <div ref={ref}>This div is {size.width} pixels wide.</div>
 */
export function useElementSize(): [size: ElementSize, ref: (node?: HTMLElement | null) => void] {
  const [elementSize, setElementSize] = useState<ElementSize>(UNDEFINED_SIZE);
  const lastSize = useRef<ElementSize>(UNDEFINED_SIZE);
  const elRef = useRef<HTMLElement | null>(null);

  // Set the initial bounds as soon as we get a reference to the element.
  const setEl = useCallback((node?: HTMLElement | null) => {
    elRef.current = node || null;
    if (node) {
      console.log(`Initial size`, elToSize(node));
      lastSize.current = elToSize(node);
      setElementSize(lastSize.current);
    } else {
      setElementSize(UNDEFINED_SIZE);
    }
  }, []);

  useLayoutEffect(() => {
    if (typeof window === 'undefined') {
      return () => void 0;
    }

    const listener = () => {
      if (elRef.current) {
        const newSize = elToSize(elRef.current);
        // Don't force a render if the size hasn't changed.
        if (
          newSize.width !== lastSize.current.width ||
          newSize.height !== lastSize.current.height
        ) {
          lastSize.current = elToSize(elRef.current);
          setElementSize(lastSize.current);
        }
      } else {
        setElementSize(UNDEFINED_SIZE);
      }
    };

    window.addEventListener('resize', listener);
    return () => window.removeEventListener('resize', listener);
  }, []);

  return [elementSize, setEl];
}
```

This doesn't suffer from this problem... but, this also relies on a window "resize" event to re-measure the element (so if e.g. an `img` loads inside your div and makes the div bigger, this code won't catch it).  `react-cool-dimensions` uses the observer API, and will correctly catch this case.

I've been trying to figure out a good way to do this even in the case where someone passes in a `ref` to us.  If it's a `{ current }` style ref, you could use `defineProperty` on it to effectively add a listener to tell you when the value changes, but that's a terrible hack.  And if it's a `function`, you can't use the same trick.

**Comment by wellyshen** [comment]
@jwalton @durdo Thank you for reporting this issue. The v1.2.0 supports the [dynamic show/hide component](https://github.com/wellyshen/react-cool-dimensions#dynamic-component).

**Comment by jwalton** [comment]
Interesting.  You could pretty much just do:

```js
import { useState } from "react";
import useDimensions from "react-cool-dimensions";
const App = () => {
  const [show, setShow] = useState(false);
  const { width, height, observe } = useDimensions();
  return (
    <>
      <button onClick={() => setShow(!show)}>Toggle</button>
      {show && (
        <div
          ref={observe}
        >
          Hi! My width is {width}px and height is {height}px
        </div>
      )}
    </>
  );
};
```

no?  Just treat `observe` like a ref?

**Comment by wellyshen** [comment]
@jwalton Seems we can replace the `ref` method with the `observe`. How do you think about it?
