### ISSUE TITLE
Losing track of element with conditional rendering

### ISSUE THREAD

**Issue by rfgamaral** [wellyshen/react-cool-dimensions#309]
# Bug Report

## Describe the Bug

I have this element that I need to track its dimensions and `react-cool-dimensions` works nicely for what I want to achieve, the problem is that this element is not always rendered and it looks like `useDimensions` loses track of the element reference.

If that didn't make sense, please see below...

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://codesandbox.io/s/beautiful-haslett-sfhji
2. A red box is loaded and its dimensions are reported correctly
3. Click the `TOGGLE` button to switch to a blue box instead
4. The red box dimensions are now reported to be 0
5. Click the `TOGGLE` button to switch back to the red box
6. **The red box dimensions remain 0**

## Expected Behavior

The red box dimensions should be correctly reported in step 6 above.

## Additional Information

- The red box is resizable if it helps to test this
- There's another third-party hook commented out where this problem does not exist

**Comment by wellyshen** [comment]
@rfgamaral Please see this [doc](https://github.com/wellyshen/react-cool-dimensions/blob/master/README.md#conditional-component).

**Comment by rfgamaral** [comment]
> @rfgamaral Please see this [doc](https://github.com/wellyshen/react-cool-dimensions/blob/master/README.md#conditional-component).

Unfortunately, either solution works for my use case...

Given other requirements, I need to run `useDimensions` on the parent (so I can't use option 2) and I also need to reuse the ref for the same element on a different hook and that hook does not accept the `observe` as a ref (can't use option 1).

**Comment by wellyshen** [comment]
@rfgamaral Can you use the option 2 then pass the ref to the parent via a callback function?

**Comment by rfgamaral** [comment]
> 
> 
> @rfgamaral Can you use the option 2 then pass the ref to the parent via a callback function?

No, I need the output from `useDimensions` in the parent too.

I might be wrong, but I think this hook suffers from [this](https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780).

**Comment by wellyshen** [comment]
@rfgamaral I think your problem can be solved by returning the ref from the observe method 🤔. How do you think about it?

**Comment by rfgamaral** [comment]
> (...)returning the ref from the observe method 🤔. How do you think about it?

That could work, but I'm not quite sure how to do it, can you give me an example?

> BTW, if you can give me a minimal code example of your use case (via code sandbox or a repo) that will be great.

I can't right now, but I'll get around it when possible, and if the solution above doesn't work :)

**Comment by wellyshen** [comment]
@rfgamaral Wait, maybe the following workaround can meet your needs:

```js
import { useRef } from "react";
import useDimensions from "react-cool-dimensions";

const App = () => {
  const someRef = useRef(null);
  const { width, height, observe } = useDimensions();

  const setRef = (el) => {
    if (!el) return;

    observe(el);
    someRef.current = el; // Used for the other hook
  }

  return (
    <>
      <button onClick={() => setShow(!show)}>Toggle</button>
      {show && (
        <div ref={setRef}>
          Hi! My width is {width}px and height is {height}px
        </div>
      )}
    </>
  );
};
```

**Comment by rfgamaral** [comment]
I won't be able to test this today, maybe tomorrow, if not, Monday for sure.

But by the looks of it could work yes. I'll let you know soon.

Thanks 😃

**Comment by rfgamaral** [comment]
@wellyshen I haven't forgotten about this... :( I just didn't answer before because I'm still doing more testing and didn't want to report back until I have a proper conclusion on all my findings.

**Comment by rfgamaral** [comment]
@wellyshen I finished looking at this and found a solution that worked for me :)

Your `setRef` solution above was in the right direction but I had to change that to a `useCallback` instead. However, that's exactly what the `observe` is and I could just use that. But then things got tricky because I wanted to use the same reference within a `useIntersection` hook (Intersection Observer) and wasn't able to find a solution that worked. I even ended up replacing the `useIntersection` hook I was using with `react-cool-inview` (😉), but it didn't fix the problem I was having (I'm still keeping your hook 😄).

In the end, I realized that there was this container element that I could use with a bit of a refactor and so I did that. A solution like that (a container element around the conditional elements), prevents a lot of issues and makes things easier. If possible, of course, might not be possible for every use case, though.

---

I'd like to point out a few things I found while looking at this hook source code:

* https://github.com/wellyshen/react-cool-dimensions/blob/master/src/index.ts#L16
  * It could make sense to change the return type here to `React.RefCallback<T>`
* I don't understand why you have types defined both in `index.ts` and `react-cool-dimensions.d.ts`. This is confusing and it's usually no needed, the types are on the source already, and building a ES modules versions should output `*.d.ts` files for you, no need to do it manually
  * This is also valid for `react-cool-inview`
* This one is related to `react-cool-inview` but I'll leave it here for now... `root?: HTMLElement` - might be worth changing this type to `Element` (`HTMLElement` extends from `Element`) since `document.querySelector` returns an `Element` (I'd imagine most people would use this to pick a root different from the default)

Thank you for your support and kudos on these great hooks :)

**Comment by wellyshen** [comment]
@rfgamaral Happy for you to find a workable solution man (👍🏻) and thank you for your suggestions I'll think about them. The reason I didn't rely on the automatically generated .d.ts is because I want to have a better readability type definition (😆)

**Comment by rfgamaral** [comment]
> The reason I didn't rely on the automatically generated .d.ts is because I want to have a better readability type definition (😆)

Although not the best practice, you can always have your types in `.d.ts` files and import them in your `.ts` files. But I'd say having the types duplicated across two files is asking for unnecessary confusion ;)

**Comment by wellyshen** [comment]
@rfgamaral Thanks bro it really helps.
