### ISSUE TITLE
Only update state on breakpoint

### ISSUE THREAD

**Issue by runar-rkmedia** [wellyshen/react-cool-dimensions#330]
# Feature Request

## Describe the Feature

When using breakpoints, it may be desirable to only receive updates if the breakpoint changes, and not on tiny changes to width/height etc.

## Describe the Solution You'd Like

I would like to add a flag to the options of the hook, `onlyUpdateOnBreakpointChange`, which only updates state if the breakpoint is changed from the previous state.

Also, to make this option very configurable, a second option is provided, `customSetState` for more advanced use-cases where the developer wants more control of when the state is updated based on any logic. For instance, only update if the delta-width is more than 50px.

## Describe Alternatives You've Considered

I've looked at using debounce, but it only sort of helps.

## Additional Information

PR is submitted as a proposal.

**Comment by wellyshen** [comment]
@runar-rkmedia All the features have been released via [v1.3.0](https://github.com/wellyshen/react-cool-dimensions/releases/tag/v1.3.0)! Thanks bro.
