### ISSUE TITLE
useBorderBoxSize and polyfill not working on Safari

### ISSUE THREAD

**Issue by rfgamaral** [wellyshen/react-cool-dimensions#365]
# Bug Report

## Describe the Bug

Using `useBorderBoxSize: true` and `polyfill: ResizeObserver` with Safari 13/14 does not seem to work.

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the CodeSandbox below and scroll the main content area
2. Observe that on Firefox/Chrome/Edge everything works as expected:
   * Light blue headers correctly sticky below the coral header ✔
3. Observe that on Safari it doesn't work as expected:
   * Light blue headers wrongly sticky behind the coral header ❌

## CodeSandbox Link

* https://codesandbox.io/s/condescending-cookies-95km9

## Expected Behavior

* Light blue headers should correctly sticky below the coral header in all browsers Firefox/Chrome/Edge/Safari

**Comment by rfgamaral** [comment]
I think I've traced this to this line:

https://github.com/wellyshen/react-cool-dimensions/blob/87e1e4067247ddee53cf8980d16bfdc7f1c9593f/src/index.ts#L112

The problem is that Safari supports `window.ResizeObserver` and thus the polyfill **is not used**. But since Safari does not support `ResizeObserverEntry.borderBoxSize`, we need to force the polyfill to be used if one needs to use `useBorderBoxSize` with this browser.

A simple fix would be to switch the conditional to `polyfill || window.ResizeObserver`, forcing the polyfill to be used **if specified**. A better fix would be to use the polyfill only if specified with `useBorderBoxSize: true`, and on a browser without support for `ResizeObserverEntry.borderBoxSize`, but that might be trickier.

For the time being I'm fixing this on my side by force using the ponyfill on all browsers like this:

```ts
(async () => {
  const module = await import("@juggle/resize-observer");
  window.ResizeObserver = module.ResizeObserver;
})();
```

**Comment by wellyshen** [comment]
@rfgamaral Sorry for the late, I will fix it soon.

**Comment by wellyshen** [comment]
@rfgamaral It should be fixed via the latest version.

**Comment by rfgamaral** [comment]
Thank you, @wellyshen, will update our apps with this :)
