### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by rfgamaral** [wellyshen/react-cool-dimensions#373]
Ever since that we started using `react-cool-dimensions` that we've been having a lot of logged errors:

> ResizeObserver loop limit exceeded

Based on [this StackOverflow](https://stackoverflow.com/a/50387233) answer it's not really something to worry about, however, it can be improved by wrapping the ResizeObserver updates in a `requestAnimationFrame`.

Here's an [example](https://github.com/souporserious/react-measure/pull/118/files) of how a similar library (not a hook) solved this.

Do you think we can get such an improvement into `react-cool-dimensions`?

**Comment by wellyshen** [comment]
@rfgamaral May I know your browser version?

**Comment by rfgamaral** [comment]
@wellyshen This is not happening to me on my browser, it's happening to our users. We are observing this `ResizeObserver loop limit exceeded` message in our [Sentry](https://sentry.io) logs. Either way, it happens on multiple browsers versions:

![image](https://user-images.githubusercontent.com/96476/109340643-2dc55500-7861-11eb-9b38-cd951bf28670.png)

**Comment by wellyshen** [comment]
@rfgamaral The list that you provided is the reproduced browses?

**Comment by rfgamaral** [comment]
I can't reproduce this issue myself, the list above is the top browsers from our users where this error is displayed.

**Comment by wellyshen** [comment]
@rfgamaral OK, I will try to reproduce it first.

**Comment by rfgamaral** [comment]
@wellyshen Were you able to reproduce this?

**Comment by wellyshen** [comment]
@rfgamaral Sorry I'm busying for a new library, will reproduce it tomorrow T_T

**Comment by wellyshen** [comment]
@rfgamaral I can't reproduce it on modern browsers with the latest two major versions (i.e. Chrome, Edge, Safari, FireFox). I think this bug only leaves in old versions. Should we still need to care about it?

**Comment by rfgamaral** [comment]
> @rfgamaral I think this bug only leaves in old versions.

We have logs from the latest browsers version, so I don't think this only happens on old versions.

> Should we still need to care about it?

In my opinion, yes.

Everyone who uses this library and has some sort of logging service (like Sentry) will probably come across this "issue". And I say "issue" because it's not really affecting functionality (as far as we know), but we have around 34k events affecting 18k users on this "issue" alone.

We could ignore it on our system, but based on the links I posted above, this should be easily fixable. I understand that without reproducing it, it's hard to understand if we are actually fixing anything. And I can't reproduce it myself either, so the best I could do is try to deploy a version with a similar fix to the ones mentioned above and see if the logs start to go away.

**Comment by wellyshen** [comment]
@rfgamaral Thank you that will be great. For now, I think the only issue is the lack of a reproduce environment to validate whether the solution is workable or not.

**Comment by rfgamaral** [comment]
> 
> 
> @rfgamaral Thank you that will be great. For now, I think the only issue is the lack of a reproduce environment to validate whether the solution is workable or not.

FYI, this is the patch I'm going to apply on our side:

```diff
diff --git a/node_modules/react-cool-dimensions/dist/index.esm.js b/node_modules/react-cool-dimensions/dist/index.esm.js
index 55a9b01..9b66260 100644
--- a/node_modules/react-cool-dimensions/dist/index.esm.js
+++ b/node_modules/react-cool-dimensions/dist/index.esm.js
@@ -61,6 +61,7 @@ var useDimensions = function useDimensions(_temp) {
   var warnedRef = useRef(false);
   var refVar = useRef(null);
   var ref = useRef(refVar == null ? void 0 : refVar.current);
+  var animationFrameRef = useRef()
   ref = refOpt || ref;
   useEffect(function () {
     if (onResize) onResizeRef.current = onResize;
@@ -138,16 +139,23 @@ var useDimensions = function useDimensions(_temp) {
       if (shouldUpdateRef.current && !shouldUpdateRef.current(next)) return;
 
       if (!shouldUpdateRef.current && breakpoints && updateOnBreakpointChange) {
-        setState(function (prev) {
-          return prev.currentBreakpoint !== next.currentBreakpoint ? next : prev;
+        animationFrameRef.current = requestAnimationFrame(function () {
+          setState(function (prev) {
+            return prev.currentBreakpoint !== next.currentBreakpoint ? next : prev;
+          });
         });
         return;
       }
 
-      setState(next);
+      animationFrameRef.current = requestAnimationFrame(function () {
+        setState(next)
+      });
     });
     observe();
     return function () {
+      if (animationFrameRef.current) {
+        cancelAnimationFrame(animationFrameRef.current)
+      }
       return unobserve();
     }; // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [// eslint-disable-next-line react-hooks/exhaustive-deps
```

I'll report back a few days after deploying this to production, and if it works, I'll open a PR with the fix :)

**Comment by wellyshen** [comment]
@rfgamaral I think the code be the following, but it's OK let's test it first.

```diff
useEffect(() => {
    if (!ref.current) return () => null;
    if (
      (!("ResizeObserver" in window) || !("ResizeObserverEntry" in window)) &&
      !polyfill
    ) {
      console.error(observerErr);
      return () => null;
    }

    let raf: number;

    // eslint-disable-next-line compat/compat
    observerRef.current = new (polyfill || window.ResizeObserver)(
      ([entry]: any) => {
        const { contentBoxSize, borderBoxSize, contentRect } = entry;

        let boxSize = contentBoxSize;
        if (useBorderBoxSize)
          if (borderBoxSize) {
            boxSize = borderBoxSize;
          } else if (!warnedRef.current) {
            console.warn(borderBoxWarn);
            warnedRef.current = true;
          }
        // @juggle/resize-observer polyfill has different data structure
        boxSize = Array.isArray(boxSize) ? boxSize[0] : boxSize;

        const width = boxSize ? boxSize.inlineSize : contentRect.width;
        const height = boxSize ? boxSize.blockSize : contentRect.height;

        if (
          width === prevSizeRef.current.width &&
          height === prevSizeRef.current.height
        )
          return;

        prevSizeRef.current = { width, height };

        const e = {
          currentBreakpoint: "",
          width,
          height,
          entry,
          observe,
          unobserve,
        };

        if (breakpoints) {
          e.currentBreakpoint = getCurrentBreakpoint(breakpoints, width);

          if (e.currentBreakpoint !== prevBreakpointRef.current) {
            if (onResizeRef.current) onResizeRef.current(e);
            prevBreakpointRef.current = e.currentBreakpoint;
          }
        } else if (onResizeRef.current) {
          onResizeRef.current(e);
        }

        const next = {
          currentBreakpoint: e.currentBreakpoint,
          width,
          height,
          entry,
        };

        if (shouldUpdateRef.current && !shouldUpdateRef.current(next)) return;

        if (
          !shouldUpdateRef.current &&
          breakpoints &&
          updateOnBreakpointChange
        ) {
          -setState((prev) =>
            -prev.currentBreakpoint !== next.currentBreakpoint ? next : prev
          -)
          +raf = requestAnimationFrame(() =>
            +setState((prev) =>
              +prev.currentBreakpoint !== next.currentBreakpoint ? next : prev
            +)
          +);
          return;
        }

        -setState(next)
        +raf = requestAnimationFrame(() => setState(next));
      }
    );

    observe();

    return () => {
      unobserve();
      +cancelAnimationFrame(raf);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    // eslint-disable-next-line react-hooks/exhaustive-deps
    JSON.stringify(breakpoints),
    useBorderBoxSize,
    observe,
    unobserve,
    updateOnBreakpointChange,
  ]);
```

**Comment by rfgamaral** [comment]
> @rfgamaral I think the following code has a better bundle size, but it's OK let's test it first.

Please bare in mind that I'm applying the patch to the `dist/index.esm.js` file, and not the source file.

**Comment by wellyshen** [comment]
@rfgamaral OK I got it.

**Comment by rfgamaral** [comment]
@wellyshen Do you think it's safe to use a standard variable to old the raf id, instead of a ref? 🤔

**Comment by wellyshen** [comment]
@rfgamaral It works the same with the ref, I do see any benefit to use the ref in our case.

**Comment by rfgamaral** [comment]
> 
> 
> @rfgamaral It works the same with the ref, I do see any benefit to use the ref in our case.

I'm confused, are you suggesting we keep using the ref or not? I just want to be clear so that I approximate the solution I'm deploying to production to the one I'll open the PR with (assuming this solves it).

**Comment by wellyshen** [comment]
@rfgamaral For our case, we don't need to use the ref, it costs more bundle size.

**Comment by rfgamaral** [comment]
I've updated the patch to this:

**`dist/index.esm.js`** `v1.3.2`
```diff
diff --git a/node_modules/react-cool-dimensions/dist/index.esm.js b/node_modules/react-cool-dimensions/dist/index.esm.js
index 55a9b01..19a06e5 100644
--- a/node_modules/react-cool-dimensions/dist/index.esm.js
+++ b/node_modules/react-cool-dimensions/dist/index.esm.js
@@ -62,6 +62,7 @@ var useDimensions = function useDimensions(_temp) {
   var refVar = useRef(null);
   var ref = useRef(refVar == null ? void 0 : refVar.current);
   ref = refOpt || ref;
+  var rafId;
   useEffect(function () {
     if (onResize) onResizeRef.current = onResize;
   }, [onResize]);
@@ -138,9 +139,12 @@ var useDimensions = function useDimensions(_temp) {
       if (shouldUpdateRef.current && !shouldUpdateRef.current(next)) return;
 
       if (!shouldUpdateRef.current && breakpoints && updateOnBreakpointChange) {
-        setState(function (prev) {
-          return prev.currentBreakpoint !== next.currentBreakpoint ? next : prev;
+        rafId = requestAnimationFrame(function () {
+          setState(function (prev) {
+            return prev.currentBreakpoint !== next.currentBreakpoint ? next : prev;
+          });
         });
+
         return;
       }
 
@@ -148,7 +152,10 @@ var useDimensions = function useDimensions(_temp) {
     });
     observe();
     return function () {
-      return unobserve();
+      unobserve();
+      if (rafId) {
+        cancelAnimationFrame(rafId)
+      }
     }; // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [// eslint-disable-next-line react-hooks/exhaustive-deps
   JSON.stringify(breakpoints), useBorderBoxSize, observe, unobserve, updateOnBreakpointChange]);

```

**Comment by wellyshen** [comment]
@rfgamaral Do you the miss the `rafId = requestAnimationFrame(function() { setState(next); })`?

**Comment by rfgamaral** [comment]
Yes I did, @wellyshen, thanks for catching that 😅

Just updated our internal PR 😊

**Comment by rubas** [comment]
@rfgamaral is anything missing here? Would be amazing to have the library throttle via animationFrame.

**Comment by rfgamaral** [comment]
@rubas I'm sorry, but I've been a bit busy, and couldn't take care of this just yet. The changes I proposed above seem to reduce our Sentry logs drastically:

![image](https://user-images.githubusercontent.com/96476/113687375-298e2200-96c0-11eb-9057-3664ea5b62b7.png)

We still have some logs for the issue, but they are mostly on Firefox, which our users don't seem to use much.

Feel free to open a PR yourself with the changes above, and I'll gladly review it. I won't be able to take care of this myself for the time being.

**Comment by wellyshen** [comment]
@rfgamaral Any updates for this issue?
