### ISSUE TITLE
just observe window?

### ISSUE THREAD

**Issue by gre** [wellyshen/react-cool-dimensions#425]
# Feature Request

I was thinking that it was possible to observe window size but apparently it's not even possible. This would be handy for any <canvas> stuff to keep in sync with window dimension.

**Comment by wellyshen** [comment]
@gre What kind of dimension that you want to trace for a window?

**Comment by gre** [comment]
basically document.body size if i want canvas to fully covered the place. i'm not sure if it's possible to do because the API expects to pass back the ref somewhere, right?

right now, my hack is to do

```js

const Main = () => {
  const { ref, width, height } = useDimensions({});
  return (
    <div ref={ref} style={{ width: "100vw", height: "100vh" }}>
      <Surface width={width} height={height}>
        <Scene />
      </Surface>
    </div>
  );
};
```

(surface is a canvas)

but this feels a hack when i just need a "useWindowSize"

**Comment by wellyshen** [comment]
@gre You can use `observe` API of v2 to watch the size of `document.body` as below:

```js
const Main = () => {
  const { observe, width, height } = useDimensions();

  useEffect(() => observe(document.body), []);

  return (
    <Surface width={width} height={height}>
        <Scene />
      </Surface>
  );
};
```

```css
body {
  width: 100vw;
  height: 100vh;
}
```

**Comment by gre** [comment]
Ok thanks!
