### ISSUE TITLE
[Question & Help] Resource Deallocation?

### ISSUE THREAD

**Issue by bkkgbkjb** [wellyshen/react-cool-dimensions#449]
Hi if my componet that gets `oberseve`d may be unmounted sometime

do I need to put `unobserve()` in `useEffect()` `return` so that resources get deallocated?

**Comment by wellyshen** [comment]
@bkkgbkjb No need, this library has implemented it internally (see [code](https://github.com/wellyshen/react-cool-dimensions/blob/master/src/index.ts#L188))
