### ISSUE TITLE
ResizeObserver polyfill does not register in hook when loaded onto window

### ISSUE THREAD

**Issue by alexieyizhe** [wellyshen/react-cool-dimensions#45]
# Bug Report

## Describe the Bug

When importing a ResizeObserver polyfill and assigning to `window.ResizeObserver`, the `useDimensions` hook does not seem to be registering the polyfill and thus does not work.

## How to Reproduce

I've tried both methods of loading the polyfill onto the `window` object:
**asynchronously**
```js
 const isResizeObserverSupported = "ResizeObserver" in window;
 if (!isResizeObserverSupported) {
    const module = await import("@juggle/resize-observer");
    (window as any).ResizeObserver = module.ResizeObserver; 
}
```

**synchronously**
```js
const isResizeObserverSupported = "ResizeObserver" in window;
if (!isResizeObserverSupported) {
  (window as any).ResizeObserver = ResizeObserver; // eslint-disable-line
}
```

Both of these on an unsupported browser will result in the hook returning 0 for all dimensions and complaining that ResizeObserver is not supported.

When importing the polyfill (async or sync) and directly providing it through the hook's `polyfill` option, it works properly.

## Expected Behavior

Adding the polyfill through the `window` object should cause the hook to work.

## Your Environment

- OS: macOS 10.15.4 (Catalina)
- Browser Firefox 68 (`ResizeObserver` unsupported)
- Version of react-cool-dimensions: v0.6.1

**Comment by wellyshen** [comment]
@alexieyizhe Sorry for the wrong example, the corrected way should be:

```js
// Wrong way
import ResizeObserver from "@juggle/resize-observer";

// Change it to
import { ResizeObserver } from "@juggle/resize-observer";
```

**Comment by alexieyizhe** [comment]
Hey @wellyshen, thanks for the response! However, in the code snippets I'm actually importing the polyfill as a named import (`module.ResizeObserver`) the correct way and the error is still occurring. 

Only when I directly pass the polyfill into the hook does it start working.

**Comment by wellyshen** [comment]
@alexieyizhe That’s wired. It works in my environment. Can you give me the information of your environment or give me a  reproduced branch for debugging?

**Comment by alexieyizhe** [comment]
@wellyshen for sure! I'm a bit busy but I'll try to give you a reproduced example sometime soon and ping you when I have that. Thanks again for following up!

**Comment by wellyshen** [comment]
@alexieyizhe Thank you man, take your time.

**Comment by alexieyizhe** [comment]
Hey @wellyshen,

I've gone and reproduced the error in [a CodeSandbox here](https://codesandbox.io/s/thirsty-glitter-pniig).

If you open it on any browsers that don't support ResizeObserver (I tried Firefox v68.0), importing the polyfill and adding it to the `window` object does not work. 

I created [another CodeSandbox](https://codesandbox.io/s/nostalgic-jackson-5di7b) where the only difference is I pass it in to the `useDimensions` hook directly as the `polyfill` option and it works on Firefox 68.

**Comment by wellyshen** [comment]
@alexieyizhe 

I can't reproduce this issue on [my developing playground](https://github.com/wellyshen/react-cool-dimensions/blob/master/demo/App/index.tsx) with Firefox v68.9.0.

But I found in the CodeSandbox, you also need to import the `ResizeObserverEntry` from the polyfill to make it work, because this hook checks [these APIs](https://github.com/wellyshen/react-cool-dimensions/blob/master/src/index.ts#L94) at start.

The code snippet as below:

```js
import { ResizeObserver, ResizeObserverEntry } from "@juggle/resize-observer";

if (!("ResizeObserver" in window)) {
  console.log("importing ResizeObserver polyfill synchronously");
  window.ResizeObserver = ResizeObserver;
  window.ResizeObserverEntry = ResizeObserverEntry;
}
```

**Comment by alexieyizhe** [comment]
@wellyshen ah that makes sense! I should've looked a bit more into it. I can make a PR to add this to the README if you're ok with that?

**Comment by wellyshen** [comment]
@alexieyizhe Does this issue also happens out of the environments of CodeSandbox? If it does, I think we can add some optional comment for the [polyfill examples](https://github.com/wellyshen/react-cool-dimensions#resizeobserver-polyfill). Because not all the environments are influenced.

**Comment by alexieyizhe** [comment]
@wellyshen I believe it does, since this was originally spotted in a repository I'm working on that uses vanilla create-react-app

**Comment by wellyshen** [comment]
@alexieyizhe Got it, PR is welcome 👍🏻

**Comment by wellyshen** [comment]
@alexieyizhe Thank you bro, I have add the comments into [README](https://github.com/wellyshen/react-cool-dimensions#resizeobserver-polyfill) along with the [v1.1.0](https://github.com/wellyshen/react-cool-dimensions/releases/tag/v1.1.0).
