### ISSUE TITLE
Type validation issue with tsc: onResize: Type 'T' does not satisfy the constraint 'HTMLElement'.

### ISSUE THREAD

**Issue by sjelfull** [wellyshen/react-cool-dimensions#461]
# Bug Report

## Describe the Bug

I'm getting a type validation issue when running `tsc`:

```node_modules/react-cool-dimensions/dist/index.d.ts:48:25 - error TS2344: Type 'T' does not satisfy the constraint 'HTMLElement'.
48     onResize?: OnResize<T>;
                           ~
node_modules/react-cool-dimensions/dist/index.d.ts:52:42 - error TS2344: Type 'T' does not satisfy the constraint 'HTMLElement'.

52   interface Return<T> extends Omit<Event<T>, "entry"> {
```

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install latest version of react-cool-dimensions
2. Use this code:
```ts
const onResize = ({ width }: { width: number}) => {
    if (ref.current) {
      ref.current.width = width
    }
  }

  const { observe, width, height } = useDimensions<HTMLDivElement>({
    onResize,
  })
```
3. Run `tsc`

## Expected Behavior

As far as I can tell you don't have any typed examples with `onResize` in the demo folder, so i'm not sure if i'm doing something wrong.

## Screenshots

![image](https://user-images.githubusercontent.com/10508/117721238-e273df00-b1df-11eb-8fc1-8dd157c24e69.png)

![image](https://user-images.githubusercontent.com/10508/117721272-ed2e7400-b1df-11eb-9dd3-6751e7e62134.png)

## Your Environment

- Device: Macbook Pro
- OS: macOS
- Version: 1.3.2 and Node v14.15.0

**Comment by wellyshen** [comment]
@sjelfull Thank you for giving this library a try. Can you migrate to the latest version to see if this issue still exists or not? BTW, there's an `OnResize` type for you.

```ts
import useDimensions, { OnResize } from "react-cool-dimensions";

const App = () => {
  const onResize: OnResize = (options) => { ... };
  const { observe } = useDimensions({ onResize });

  // ...
  );
};
```
