### ISSUE TITLE
BUG: If element has zero width, entry is not defined

### ISSUE THREAD

**Issue by sirkrisp** [wellyshen/react-cool-dimensions#674]
# Bug Report

## Describe the Bug

If element has zero width, `entry` as returned by `useDimensions` is undefined. Only after width is larger than 1 px, entry will be defined.

## CodeSandbox Link

https://codesandbox.io/s/throbbing-water-4ujwul?file=/src/App.js

## Expected Behavior

Entry should be defined with width 0

**Comment by wellyshen** [comment]
@sirkrisp The `entry` reflects the [ResizeObserverEntry](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry) of the callback of [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver#parameters). The `entry` only be initialized once the call is triggered while the size of the element is changed.

**Comment by sirkrisp** [comment]
@wellyshen Thanks for your reply, understood. I think it would be great if there was variable that indicates when we can trust the dimensions as returned by `useDimensions`. Because, by the same reasoning, the entry for the 1px element shouldn't be defined as well, right (and width shouldn't be zero)? And even if it is due to how React renders elements, there might be a way to make `useDimensions` behave like one "would expect".

**Comment by wellyshen** [comment]
@sirkrisp It's OK I can understand what you meant. Actually, that's the behavior of the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver#parameters). So I designed the initial value of the `entry` as `undefined`. Isn't that enough?

**Comment by sirkrisp** [comment]
@wellyshen In my scenario, I had to create a Placeholder component that relies on useDimensions (It's a placeholder for an absolute positioned element). The placeholder is animated, so the initial dimensions matter. The placeholder also has to work when the target element has zero width/height. And in this special scenario, I cannot rely on the entry being undefined because it stays undefined for elements with zero width/height.

**Comment by wellyshen** [comment]
@sirkrisp Why don't you just use the [width and height](https://github.com/wellyshen/react-cool-dimensions#return-object) state? Their initial value is `0`.

**Comment by sirkrisp** [comment]
@wellyshen Because the placeholder is animated, and this would result in an unwanted animation from zero to the actual width/height. Basically I cannot differentiate whether the target element has actually zero width/height or whether the element hasn't really rendered yet, if that makes sense.

**Comment by wellyshen** [comment]
@sirkrisp Hmm... maybe we can have an initial width/height option. Do you think that will be helpful?

**Comment by sirkrisp** [comment]
@wellyshen That would be extremely useful!

**Comment by wellyshen** [comment]
@sirkrisp Alright will take time for that. Also, a PR is welcome. What I think is a simple "initialWidth" and "initialHight" their default values are 0.

**Comment by sirkrisp** [comment]
@wellyshen Will create a PR later today or tomorrow. Actually, I am not sure about the initialWidth/Height option - because those I could also pass into the component. What I am really looking for is a simple variable that helps me to differentiate those two special cases above. Maybe I just propose something and then you can decide (won't be much to code anyway)

**Comment by wellyshen** [comment]
@sirkrisp No problem mate. A proposal might be great 👍🏻

**Comment by wellyshen** [comment]
@sirkrisp Any updates?

**Comment by sirkrisp** [comment]
@wellyshen I'm so sorry, I was very busy and completely forgot about it but I still want to implement it. In the meantime, if you do not want this issue to be open you can close it (will still keep you updated about my progress here).

**Comment by sirkrisp** [comment]
@wellyshen I implemented the changes here: https://github.com/sirkrisp/react-cool-dimensions/tree/zero-width 
Can you have a look? Thanks!

**Comment by sirkrisp** [comment]
@wellyshen I basically just initialised width and height with null and only after the elements bounds those variables are populated with the correct dimensions. I think initialising width and height with 0, which is a valid dimension, is not ideal but I'm open to discuss. Best, Kris

**Comment by wellyshen** [comment]
@sirkrisp Sorry for the late, the `null` values for the width and height make sense, would you like to raise a PR for that?

**Comment by sirkrisp** [comment]
@wellyshen thanks for your awesome work and accepting my PR! Closing this issue now
